[build]
  # The directory containing the static files
  publish = "/"
  
  # No build command since we're serving static files
  command = ""

# Redirects for SPA (if needed in the future)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to ensure proper security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://cdnjs.cloudflare.com https://cdn.jsdelivr.net;"
